In [23]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
data=pd.DataFrame({"student name":["Ram","Ganesh","Anand","Mukesh","Shankar","Chinmay","Aman"],"gmat":[750,720,710,690,670,650,600],"workexp":[0,1,2,0,4,6,1],"international awards":[4,2,0,1,2,2,0],"admission":["Yes","Yes","No","No","Yes","Yes","No"]})
data

student name  gmat  workexp  international awards admission
0          Ram   750        0                     4       Yes
1       Ganesh   720        1                     2       Yes
2        Anand   710        2                     0        No
3       Mukesh   690        0                     1        No
4      Shankar   670        4                     2       Yes
5      Chinmay   650        6                     2       Yes
6         Aman   600        1                     0        No

In [3]:
query_data=pd.DataFrame({"student name":["Amit"],"gmat":[700],"workexp":[1],"international awards":[2]})
query_data

student name  gmat  workexp  international awards
0         Amit   700        1                     2

In [4]:
data.iloc[ : ,0:-1]

student name  gmat  workexp  international awards
0          Ram   750        0                     4
1       Ganesh   720        1                     2
2        Anand   710        2                     0
3       Mukesh   690        0                     1
4      Shankar   670        4                     2
5      Chinmay   650        6                     2
6         Aman   600        1                     0

In [5]:
feature_data=np.array(data.iloc[ : ,1:-1])
feature_data

array([[750,   0,   4],
       [720,   1,   2],
       [710,   2,   0],
       [690,   0,   1],
       [670,   4,   2],
       [650,   6,   2],
       [600,   1,   0]], dtype=int64)

In [6]:
data.iloc[:,-1:]

admission
0       Yes
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No

In [7]:
target_data=np.array(data.iloc[ : ,-1:])
target_data

array([['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No']], dtype=object)

In [12]:
q_point= np.array(query_data.iloc[:,1:])
q_point

array([[700,   1,   2]], dtype=int64)

In [13]:
distances=np.sqrt(np.sum(np.square(q_point-feature_data),axis=1))
distances

array([ 50.04997502,  20.        ,  10.24695077,  10.09950494,
        30.14962686,  50.24937811, 100.019998  ])

# distance btw amit and ram is 50.04997502


In [14]:
np.sort(distances)

array([ 10.09950494,  10.24695077,  20.        ,  30.14962686,
        50.04997502,  50.24937811, 100.019998  ])

In [15]:
sort_index=sort_index=np.argsort(distances)
sort_index

array([3, 2, 1, 4, 0, 5, 6], dtype=int32)

In [19]:
k=5
top_k=sort_index[0:5]
top_k

array([3, 2, 1, 4, 0], dtype=int32)

In [17]:
data

student name  gmat  workexp  international awards admission
0          Ram   750        0                     4       Yes
1       Ganesh   720        1                     2       Yes
2        Anand   710        2                     0        No
3       Mukesh   690        0                     1        No
4      Shankar   670        4                     2       Yes
5      Chinmay   650        6                     2       Yes
6         Aman   600        1                     0        No

# 3 closest to amit are mukesh,anand and last ganesh

In [20]:
nn_classes=target_data[top_k]
nn_classes

array([['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes']], dtype=object)

In [30]:
pred=stats.mode(nn_classes)
pred[0][0][0]

'Yes'

yes amit will get admission